language: php

sudo: false

php:
 - 5.6.18

before_install:
- composer require phpunit/phpunit:4.8.* satooshi/php-coveralls:dev-master
- composer install --dev

script:
 - mkdir -p build/logs
 - phpunit --coverage-clover build/logs/clover.xml

after_script:
 - php vendor/bin/coveralls -v

#install:
 # - ./bin/ci/install_dependencies.sh
 # - php vendor/vendors.php

notifications:
email: false
